menu:
  archives: /archives
  RAY: http://www.rayliao.com/
  github: https://github.com/rayliao
  rss: /atom.xml

favicon: /favicon.jpeg
logo: /favicon.jpeg

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
gitalk:
  on: false
  owner: rayliao
  repo: blog
  admin: ['rayliao']
  accessToken: 00f4c7413df974956ac1ad555e33bcc24fa06e25

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2016
