menu:
    博客: /blog
    微博: http://weibo.com/574954033
    RAY: http://www.rayliao.com/
    github: https://github.com/rayliao

favicon: /favicon.jpeg
logo: /favicon.jpeg

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2017
